"""empty message

Revision ID: 69c65fc23da7
Revises: 9f1fd8146c8c
Create Date: 2024-06-01 16:54:57.851723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c65fc23da7'
down_revision = '9f1fd8146c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=150), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
