"""empty message

Revision ID: 6a84b8ca5209
Revises: 24d4a6d2c6de
Create Date: 2024-06-03 21:07:19.414857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a84b8ca5209'
down_revision = '24d4a6d2c6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'experiences',
        sa.Column('experience_id', sa.Integer(), nullable=False),
        sa.Column('resume_id', sa.Integer(), sa.ForeignKey('resumes.id')),
        sa.Column('job_title', sa.String(length=255), nullable=False),
        sa.Column('company_name', sa.String(length=255), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('job_description', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('experience_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiences')
