"""empty message

Revision ID: 8d41422aca01
Revises: 761b2f42d59c
Create Date: 2024-06-03 21:23:05.137595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d41422aca01'
down_revision = '761b2f42d59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'candidate_skills',
        sa.Column('candidate_skill_id', sa.Integer(), nullable=False),
        sa.Column('resume_id', sa.Integer(), nullable=False),
        sa.Column('skill_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name='fk_candidate_skills_resume_id'),
        sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], name='fk_candidate_skills_skill_id'),
        sa.PrimaryKeyConstraint('candidate_skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_skills')