"""empty message

Revision ID: 968c69258504
Revises: 
Create Date: 2024-06-02 22:07:59.440328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968c69258504'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_app',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('salary_range', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=120), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('text_file_path', sa.String(length=100), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('resumes')
    op.drop_table('job_app')
    # ### end Alembic commands ###
