"""Added filename column to Resume model

Revision ID: 9c6786215ecb
Revises: cb4a5d734248
Create Date: 2024-06-01 20:01:49.666221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c6786215ecb'
down_revision = 'cb4a5d734248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=100), nullable=True))
        batch_op.drop_column('resume_files')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_files', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
