"""empty message

Revision ID: fed9df350b43
Revises: 51f1600db5a4
Create Date: 2024-06-03 21:16:25.207114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed9df350b43'
down_revision = '51f1600db5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'languages',
        sa.Column('language_id', sa.Integer(), nullable=False),
        sa.Column('language_name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('language_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('languages')